{
 "title": "Waku Analysis",
 "description": "Metrics for Waku nodes written in Nim",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "nwaku_.*" }
  ]
 },
 "panels": [
  {
   "title": "At a glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Libp2p PubSub Peers",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_pubsub_peers{instance=~\"[[instance]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node start times (UTC)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"[[instance]]\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(libp2p_network_bytes_total{instance=~\"[[instance]]\", direction=\"in\"}[15m]))/1000000/(900)*8",
     "legendFormat": "{{instance}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(libp2p_network_bytes_total{instance=~\"[[instance]]\", direction=\"out\"}[15m]))/1000000/(900)*8",
     "legendFormat": "{{instance}}:{{direction}}"
    }
   ]
  },
  {
   "title": "Messages (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total{instance=~\"[[instance]]\"}[1m]))",
     "legendFormat": "{{type}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Waku Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_peers_errors{instance=~\"[[instance]]\"}[$__rate_interval]))",
     "legendFormat": "peer {{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_store_errors{instance=~\"[[instance]]\"}[$__rate_interval]))",
     "legendFormat": "store {{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_node_errors{instance=~\"[[instance]]\"}[$__rate_interval]))",
     "legendFormat": "node {{type}}"
    }
   ]
  },
  {
   "title": "Total Content Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "count(count by (contentTopic)(waku_node_messages_total))",
     "legendFormat": "content topics"
    }
   ]
  },
  {
   "title": "Waku version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "waku_version{instance=~\"[[instance]]\"}",
     "legendFormat": "{{instance}}:{{version}}"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Node Filters",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "waku_node_filters{instance=~\"[[instance]]\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Node Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "waku_node_errors{instance=~\"[[instance]]\"}",
     "legendFormat": "{{type}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Pubsub Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "libp2p_pubsub_topics {instance=~\"[[instance]]\"}",
     "legendFormat": "Topics: {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_subscriptions_total {instance=~\"[[instance]]\"}",
     "legendFormat": "Subscriptions: {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_unsubscriptions_total {instance=~\"[[instance]]\"}",
     "legendFormat": "Unsubscriptions: {{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P PubSub Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(libp2p_pubsub_peers{instance=~\"[[instance]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(libp2p_peers{instance=~\"[[instance]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Validations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_pubsub_validation_success_total{instance=~\"[[instance]]\"}",
     "legendFormat": "success {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_validation_failure_total{instance=~\"[[instance]]\"}",
     "legendFormat": "failure {{instance}}"
    },
    {
     "expr": "libp2p_pubsub_validation_ignore_total{instance=~\"[[instance]]\"}",
     "legendFormat": "ignore {{instance}}"
    }
   ]
  },
  {
   "title": "LibP2P Open Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type)(libp2p_open_streams{instance=~\"[[instance]]\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total{instance=~\"[[instance]]\"}",
     "legendFormat": "Attempts: {{instance}}"
    },
    {
     "expr": "libp2p_failed_dials_total{instance=~\"[[instance]]\"}",
     "legendFormat": "Failed: {{instance}}"
    },
    {
     "expr": "libp2p_successful_dials_total{instance=~\"[[instance]]\"}",
     "legendFormat": "Successful: {{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(process_open_fds{instance=~\"[[instance]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=~\"[[instance]]\"}",
     "legendFormat": "Nim total memory: {{instance}}"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=~\"[[instance]]\"}",
     "legendFormat": "Nim occupied memory: {{instance}}"
    },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes{instance=~\"[[instance]]\"}",
     "legendFormat": "Nim total heap: {{instance}}"
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=~\"[[instance]]\"}",
     "legendFormat": "{{instance}}  {{type_name}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(process_virtual_memory_bytes{instance=~\"[[instance]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(process_resident_memory_bytes{instance=~\"[[instance]]\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bridge (10m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "increase(waku_bridge_transfers_total{instance=~\"[[instance]]\"}[10m])",
     "legendFormat": "{{fleet}} : {{type}}"
    },
    {
     "expr": "increase(envelopes_valid_total{instance=~\"bridge*[[instance]]\"}[10m])",
     "legendFormat": "{{fleet}} : v1_envelopes"
    },
    {
     "expr": "increase(waku_node_messages_total{instance=~\"bridge*[[instance]]\"}[10m])",
     "legendFormat": "{{fleet}} : v2_messages"
    },
    {
     "expr": "increase(envelopes_dropped_total{instance=~\"bridge*[[instance]]\"}[10m])",
     "legendFormat": "{{fleet}} : v1_envelopes_dropped ({{reason}})"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "connected_peers{instance=~\"bridge*[[instance]]\"}",
     "legendFormat": "v1_connected_peers"
    },
    {
     "expr": "libp2p_pubsub_peers{instance=~\"bridge*[[instance]]\"}",
     "legendFormat": "v2_connected_peers"
    }
   ]
  },
  {
   "title": "Store/Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waku Store Queries (Postgres) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "increase(waku_store_queries{instance=~\"nwaku_postgres:8003\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Store Queries (SQLite) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "increase(waku_store_queries{instance=~\"nwaku_sqlite:8004\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Waku Archive Errors (Postgres) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_archive_errors{instance=~\"nwaku_postgres:8003\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_store_errors{instance=~\"nwaku_postgres:8003\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Waku Archive Errors (SQLite) (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "sum by (type)(increase(waku_archive_errors{instance=~\"nwaku_:8004\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type)(increase(waku_store_errors{instance=~\"nwaku_sqlite:8004\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Waku Archive Query Duration (Postgres)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_query_duration_seconds_bucket{instance=~\"nwaku_postgres:8003\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Query Duration (SQLite)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_query_duration_seconds_bucket{instance=~\"nwaku_sqlite:8004\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Insert Duration (Postgres)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_insert_duration_seconds_bucket{instance=~\"nwaku_postgres:8003\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Waku Archive Insert Duration (SQLite)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(waku_archive_insert_duration_seconds_bucket{instance=~\"nwaku_sqlite:8004\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}